### PR TITLE
fix: styles for paymentsummary

### LINKED ISSUE #2944: Fix copy items with labels on transaction screens
Currently we have 2 different stylings of 2 very similar components that appear across different actions in the extension:

image

I propose following improvements:

- [x] Label: text-sm medium, gray800 dark: neutral200
- [x] Copy: text-lg regular, gray600 dark: neutral400
- [x] Delete brackets ( ) from fiat element
- [x] ideally it could be just the same defined component, but that may be a seperate PR

CleanShot 2023-12-19 at 20 07 43@2x

CleanShot 2023-12-19 at 20 08 32@2x

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

Fixes #2944

### CODE REVIEW

File: src/app/components/PaymentSummary/index.tsx [hunk 1]
```diff
@@ -4,50 +4,45 @@ import { useSettings } from "~/app/context/SettingsContext";
...
-            className="text-gray-500 dark:text-neutral-500"
-            data-testid="fiat_amount"
-          >
-            {" "}
-            (~{fiatAmount})
-          </span>
-        )}
-      </dd>
-      {amountAlt && <dd className="text-gray-400">{amountAlt}</dd>}
+    <dl className="space-y-4">
```
Comment (pavanjoshi914) [inline src/app/components/PaymentSummary/index.tsx:16]: this have no effect. maybe add this style on div element instead of dl. but spacing is quite large maybe just remove this

Comment (reneaaron) [reply src/app/components/PaymentSummary/index.tsx:16]: Without `space-y-4`:
image

With `space-y-4`:
image

Comment (reneaaron) [reply src/app/components/PaymentSummary/index.tsx:16]: Implemented spacing according to the designs, space is needed desperately.
