### PR TITLE
fix: core-lightning apis

### LINKED ISSUE #2910: [BUG] CLN Connection with Rune Shows Balances as `NaN`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Balance and historical incoming tx amounts all show as `NaN`

### Screenshots [optional]

image

### Steps To Reproduce

1. Connect via CLN with a Rune (in this case from StartOS)
2. Connection completes successfully
3. Balance and historical incoming tx amounts all show as `NaN`
    - Historical outbound tx amounts display properly

### Expected behavior

Correct balances and payment history display in sats

### Alby information

Alby 3.4.1 Firefox extension

### Device information

Linux 6.1, Firefox 120

### Additional context

_No response_

### Are you working on this?

None

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

Fixes #2910

### CODE REVIEW

File: src/extension/background-script/connectors/commando.ts [hunk 1]
```diff
@@ -303,10 +306,16 @@ export default class Commando implements Connector {
       params: {},
       rune: this.config.rune,
     })) as CommandoListFundsResponse;
-    const lnBalance = response.channels.reduce(
-      (balance, channel) => balance + channel.channel_sat,
-      0
-    );
+    const lnBalance = response.channels
```
Comment (reneaaron) [inline src/extension/background-script/connectors/commando.ts:309]: https://github.com/ElementsProject/cln-application/blob/main/apps/frontend/src/store/AppContext.tsx#L139

Comment (bumi) [reply src/extension/background-script/connectors/commando.ts:309]: maybe add it as comment?

Comment (reneaaron) [inline src/extension/background-script/connectors/commando.ts:309]:
```suggestion
    // https://github.com/ElementsProject/cln-application/blob/main/apps/frontend/src/store/AppContext.tsx#L139
    const lnBalance = response.channels
```
