### PR TITLE
fix: change the styling for the galoy connector screen in dark theme mode

### LINKED ISSUE #2656: [Feature] <Improve visibility in dark mode for connector screens>
### Feature description

The text in connector screen is not clearly visible in dark mode.
image

### Describe the solution

**change the font color**

### Describe alternatives

Change the (opacity & color) of the background.

### Additional context

_No response_

### Are you working on this?

None

### PR DESCRIPTION
**Pull request by Rithvik-padma**
### Describe the changes you have made in this PR

Changed the styling of galoy connector screen in dark mode

### Link this PR to an issue [optional]

Fixes #2656

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes 

image

### How has this been tested?

Tested manually by trying to add a new account though connector in dark mode and checked for the same in light theme mode too.

### Checklist

- [x] Self-review of changed code
- [x] Manual testing
- [x] Added automated tests where applicable
- [x] Darkmode
- [x] Responsive layout

### CODE REVIEW

**Comment by Rithvik-padma** [comment]
@rolznz Please review this PR.
Thanks!

**Comment by Rithvik-padma** [comment]
I think currently we are using the previous logo of Bitcoin beach wallet.
This PR #2655 will update the logo and name.

File: src/app/components/ConnectorForm/index.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ function ConnectorForm({
 
   return (
     <form onSubmit={onSubmit}>
-      <div className="max-w-xl mx-auto mt-6 relative bg-white dark:bg-surface-02dp p-7 shadow rounded-lg">
+      <div className="max-w-xl mx-auto mt-6 relative bg-white dark:bg-transparent dark:bg-surface-02dp p-7 shadow rounded-lg">
```
Comment (rolznz) [inline src/app/components/ConnectorForm/index.tsx:59]: there is a duplicated bg class here, can you remove it?

File: src/app/screens/connectors/ConnectGaloy/index.tsx [hunk 2]
```diff
@@ -168,26 +168,31 @@ export default function ConnectGaloy(props: Props) {
...
-              // eslint-disable-next-line react/jsx-key
-              <br />,
-              // eslint-disable-next-line react/jsx-key
-              <b></b>,
-            ]}
-          />
-          <label htmlFor="jwt" className="block font-medium text-gray-700">
+          <label
+            htmlFor="jwt"
+            className="block font-medium text-gray-800 dark:text-white"
```
Comment (rolznz) [inline src/app/screens/connectors/ConnectGaloy/index.tsx:194]: was it intentional to change the light mode styles too?

Comment (Rithvik-padma) [reply src/app/screens/connectors/ConnectGaloy/index.tsx:194]: Yes I changed the label's font color so that is similar to the font color in connector forms. For other connector screens the `Textfield` component is used and there the label has a font color style is `text-gray-800` so I have used the same here too.

File: src/app/components/ConnectorForm/index.tsx (hunk 1 above)
Comment (Rithvik-padma) [reply src/app/components/ConnectorForm/index.tsx:59]: Sure I will remove it.

Comment (Rithvik-padma) [reply src/app/components/ConnectorForm/index.tsx]: removed it!

**Comment by Rithvik-padma** [comment]
@rolznz I have made some changes as per the review.
Thanks!

**Review by rolznz — APPROVED** [review]
tACK

**Comment by rolznz** [comment]
Thanks @Rithvik-padma !
