### PR TITLE
fix: ln address regex

### LINKED ISSUE #1437: Connection problem or invalid lnurl / lightning address.
### Describe the bug

I tried to send sats to a video youtube and I see this error: Connection problem or invalid lnurl / lightning address.

### Screenshots (If Any)

Captura de tela de 2022-09-13 11-23-39

### To Reproduce

1- Go to: https://www.youtube.com/watch?v=PqNRpStZRAE
2- Go to blue alby icon from extension and try to send sats

### Expected behavior

Able to send sats

### Alby information

- Alby Version: 1.15.1

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Makes [.] after @ mandatory as it can confuse for links with @ in between

For example:
`⚡️ https://tippin.me/@njelsalvador` is a valid ln address as per the old regex as it has `⚡️ + words + @ + words`

Changed it to:
`⚡️ + words + @ + words + .(dot) + words`

### Link this PR to an issue

Fixes #1437 

### Type of change (Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

https://www.youtube.com/watch?v=PqNRpStZRAE

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

File: src/extension/content-script/batteries/helpers.ts [hunk 1]
```diff
@@ -7,7 +7,9 @@ import { ExtensionIcon } from "../../background-script/actions/setup/setIcon";
 export const findLightningAddressInText = (text: string): string | null => {
   // The second lightning emoji is succeeded by an invisible
   // variation selector-16 character: https://regex101.com/r/Bf2GpN/1
```
Comment (escapedcat) [inline src/extension/content-script/batteries/helpers.ts:9]: Is the regex link still matching this? Should it?

Comment (im-adithya) [reply src/extension/content-script/batteries/helpers.ts:9]: Yeah thought of it before, it just has the regex of two lightning emojis so that we won't have to change

**Review by escapedcat — APPROVED** [review]
ACK (tested with monvol)
