### PR TITLE
fix: jest warnings

### LINKED ISSUE #1229: Chore: act warnings in jest tests
### Describe the issue

We currently get some `act`-warnings when running the uni tests

### Screenshots

1.
```sh
 PASS  src/extension/background-script/actions/allowances/__tests__/get.test.ts
  get allowance
    ✓ get allowance (249 ms)

  console.error
    Warning: An update to ConfirmPayment inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at ConfirmPayment (lightning-browser-extension/src/app/screens/ConfirmPayment/index.tsx:29:43)
        at basename (/alby--lightning-browser-extension/node_modules/react-router/umd/react-router.development.js:821:7)
        at basename (/alby--lightning-browser-extension/node_modules/react-router/umd/react-router.development.js:734:7)

      124 |                 remember={rememberMe}
      125 |                 onRememberChange={(event) => {
    > 126 |                   setRememberMe(event.target.checked);
          |                   ^
      127 |                 }}
      128 |                 budget={budget}
      129 |                 onBudgetChange={(event) => setBudget(event.target.value)}
```

2.
```sh
 PASS  src/extension/background-script/actions/accounts/__tests__/info.test.ts
  account info
    ✓ get account info (2 ms)

  console.error
    Warning: An update to Transition inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
```

### To Reproduce

1. Checkout master
1. `yarn test:unit`

### Expected behavior

No warnings occur

### Additional context

Usually wrapping certain test commands in `act` helps

### Are you working on this issue?

No

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Fixes jest warnings.

### Link this PR to an issue

Fixes #1229

### Type of change (Remove other not matching type)

- `chore`: remove warnings in tests

### How has this been tested?

Ran tests w/o warnings

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]

File: src/app/screens/LNURLPay/index.tsx [hunk 1]
```diff
@@ -314,10 +314,10 @@ function LNURLPay() {
                   <dl>
                     <>
                       {formattedMetadata(details.metadata).map(([dt, dd]) => (
-                        <>
+                        <div key={dt}>
```
Comment (escapedcat) [inline src/app/screens/LNURLPay/index.tsx:317]: ~Hm, issue with this is, that this is not valid html anymore.~
~Within `dl` only `dt`/`dd` can exist.~
That was what I wanted to write, but turns out:
image
(via https://validator.w3.org/nu/#textarea)
Weird, but ok. A `div` within a `ul` is not valid. Thought it will be the same issue within a `dl`.

But only using `dt` as key could be an issue maybe. If i.e. for some reason a `dt` could be not unique. Maybe this should be combined with an `index`?

Comment (im-adithya) [reply src/app/screens/LNURLPay/index.tsx]: Done! Changed it to use Fragment and use index for key.

**Review by escapedcat — APPROVED** [review]
Nice, didn't know about `Fragment` 👏

**Review by escapedcat — CHANGES_REQUESTED** [review]
If I run:`yarn test:unit`

I get this:
```sh
 PASS  src/extension/background-script/actions/accounts/__tests__/all.test.ts
  account all
    ✓ get all accounts (1 ms)

  console.error
    Warning: An update to ConfirmPayment inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at ConfirmPayment (/src/app/screens/ConfirmPayment/index.tsx:32:5)
        at basename (/node_modules/react-router/umd/react-router.development.js:821:7)
        at basename (/node_modules/react-router/umd/react-router.development.js:734:7)

      128 |                 remember={rememberMe}
      129 |                 onRememberChange={(event) => {
    > 130 |                   setRememberMe(event.target.checked);
          |                   ^
      131 |                 }}
      132 |                 budget={budget}
      133 |                 onBudgetChange={(event) => setBudget(event.target.value)}

      at call (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at error (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at setRememberMe (src/app/screens/ConfirmPayment/index.tsx:130:19)
      at HTMLUnknownElement.apply (node_modules/react-dom/cjs/react-dom.development.js:4164:14)

  console.info
    Loading DB data from storage

      at info (src/extension/background-script/db.ts:46:13)

 PASS  src/extension/background-script/actions/payments/__tests__/all.test.ts
  payment all
    ✓ get all payments (59 ms)

  console.error
    Warning: An update to Transition inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Transition (/node_modules/@headlessui/react/dist/headlessui.dev.cjs:5173:9)
        at div
        at remember (/src/app/components/BudgetControl/index.tsx:16:3)
        at div
        at div
        at div
        at children (/src/app/components/Container.tsx:9:22)
        at div
        at ConfirmPayment (/src/app/screens/ConfirmPayment/index.tsx:32:5)
        at basename (/node_modules/react-router/umd/react-router.development.js:821:7)
        at basename (/node_modules/react-router/umd/react-router.development.js:734:7)

      at call (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at error (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at node_modules/@headlessui/react/dist/headlessui.dev.cjs:5199:7
      at create (node_modules/react-dom/cjs/react-dom.development.js:23150:26)

  console.error
    Warning: An update to Transition inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Transition (/node_modules/@headlessui/react/dist/headlessui.dev.cjs:5173:9)
        at div
        at remember (/src/app/components/BudgetControl/index.tsx:16:3)
        at div
        at div
        at div
        at children (/src/app/components/Container.tsx:9:22)
        at div
        at ConfirmPayment (/src/app/screens/ConfirmPayment/index.tsx:32:5)
        at basename (/node_modules/react-router/umd/react-router.development.js:821:7)
        at basename (/node_modules/react-router/umd/react-router.development.js:734:7)

      at call (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at error (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at node_modules/@headlessui/react/dist/headlessui.dev.cjs:5205:7
      at create (node_modules/react-dom/cjs/react-dom.development.js:23150:26)
```

You also get these?

File: src/app/screens/ConfirmPayment/index.test.tsx [hunk 2]
```diff
@@ -71,7 +71,9 @@ describe("ConfirmPayment", () => {
       );
     });
 
-    await user.click(screen.getByText("Remember and set a budget"));
+    await act(() => {
```
Comment (lisabaut) [inline src/app/screens/ConfirmPayment/index.test.tsx:74]: 👍

**Review by lisabaut — APPROVED** [review]
Thanks

**Comment by im-adithya** [comment]
> You also get these?

Nope, didn't get them both locally and [here](https://github.com/getAlby/lightning-browser-extension/runs/7818265715?check_suite_focus=true)

**Review by escapedcat — APPROVED** [review]
Ok then :)
