### PR TITLE
fix: style disabled state of inputs

### LINKED ISSUE #2292: Style disabled state of inputs
This design is dependent and assumes this update https://github.com/getAlby/lightning-browser-extension/issues/2237 to input will occur (mostly moving fiat amount inside the input) and that those corrections to helper (amount) input will be made https://github.com/getAlby/lightning-browser-extension/issues/2291

Current disabled input state (eg. Nostr public key) look the same as filled state, which may cause bad UX for people in some cases. 

I propose making disabled state visually different, like this (only inside of the input changes the styling):

Light theme: input bg: gray50
Dark theme: input bg: surface16dp
Text inside the input (both themes): gray500

Screenshot 2023-03-29 at 23 58 47

### PR DESCRIPTION
**Pull request by Pratik-A-N**
### Description

I have made the changes in the inputNode component className prop which had classNames function in which I added the extra condition to check whether the field is disabled or not and applied the styles as desired in the issue discription

### Link this PR to an issue

Fixes #2292

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]

Screenshot from 2023-03-31 07-19-44
Screenshot from 2023-03-31 07-20-11

### How has this been tested?

The Public Key field can be now checked and it is according to the required UI which reflects that it is disabled in both light and dark modes. It can be seen in the above images.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by stackingsaunter** [comment]
Thank you @Pratik-A-N for your contribution! 🚀

I tested the build but iI see different styling than in the issue, compare:


Screenshot 2023-03-31 at 11 30 31
Screenshot 2023-03-31 at 11 31 33

And then desired styling:
image

Seems like in Light theme, neither text color or input bg is rendering correctly, and in dark mode text color is not rendering correctly. Do you have an idea why is that happening?

Also, seeing it live I think I there can be better colors for dark mode that I initially chose in the issue. Could you change disabled text into **neutral500** and and surface into **surface-01dp**? Sorry for inconvenience! 

Screenshot 2023-03-31 at 12 12 38

**Comment by Pratik-A-N** [comment]
Screenshot from 2023-03-31 07-20-11
I'm getting this result after using bg-surface-01dp and for the light theme I checked bg and the text color are working I think the change is not recognizable due to the background contrast

File: src/app/components/form/Input/index.tsx [hunk 1]
```diff
@@ -38,10 +38,12 @@ export default function Input({
       name={name}
       id={id}
       className={classNames(
-        "block w-full placeholder-gray-500 dark:placeholder-neutral-600 dark:text-white",
-        !suffix && !endAdornment
-          ? `${outerStyles} focus:ring-orange-bitcoin focus:border-orange-bitcoin focus:dark:border-orange-bitcoin focus:ring-1`
-          : "pr-0 border-0 focus:ring-0 bg-transparent"
```
Comment (im-adithya) [inline src/app/components/form/Input/index.tsx:44]: Instead of doing the below changes, here you can:

- Modify `outerStyles` to remove unnecessary background and text styling (I wonder how it reached there)
```js
const outerStyles = "rounded-md border border-gray-300 dark:border-neutral-800 transition duration-300";
```
- Remove `bg-transparent` from line 44 (as `suffix` and `endAdornment` don't influence the background and text)
- Use `disabled` separately to control the background and text styling wholly, instead of `suffix` and `endAdornment`
```js
//...
!suffix && !endAdornment
  ? `${outerStyles} focus:ring-orange-bitcoin focus:border-orange-bitcoin focus:dark:border-orange-bitcoin focus:ring-1`
  : "pr-0 border-0 focus:ring-0",
disabled
  ? "bg-gray-50 dark:bg-surface-01dp text-gray-500 dark:text-neutral-500"
  : "bg-white dark:bg-black dark:text-white"
```

Comment (Pratik-A-N) [reply src/app/components/form/Input/index.tsx:44]: Thank you for suggesting changes, I will do the mentioned changes

**Comment by Pratik-A-N** [comment]
@stackingsaunter @im-adithya can you please review it again ??

**Review by im-adithya — APPROVED** [review]

**Review by stackingsaunter — APPROVED** [review]
