### PR TITLE
fix: remove dynamic classes from badges

### LINKED ISSUE #2813: Regression: Budget and Login not green color on connected sites
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Budget and Login not green color on connected sites

Captura de tela de 2023-10-12 10-15-11

### Screenshots [optional]

_No response_

### Steps To Reproduce

Visit connected sites and see Login and budget

### Expected behavior

See Login and Budget in green color

### Alby information

Alby: 3.3

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

Fixes #2813

Currently badges are not rendered as those classes are dynamically constructed which should be avoided: 

https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -709,7 +709,6 @@ export interface RequestInvoiceArgs {
 export type Transaction = {
   amount?: string;
   boostagram?: Invoice["boostagram"];
-  badges?: Badge[];
```
Comment (reneaaron) [inline src/types.ts:712]: This has never been in use, so I deleted it.

Comment (pavanjoshi914) [reply src/types.ts:712]: thanks for noticing it

**Review by pavanjoshi914 — APPROVED** [review]
tACK
