### PR TITLE
fix: improved validation with latest nostr-tools validateEvent

### LINKED ISSUE #2446: [BUG] window.nostr.signEvent does not validate the input and returns undefined for invalid input
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently if you call signEvent with one of the following, it returns undefined rather than throwing an exception. This leads to confusion.

`const signedEvent = await window.nostr.signEvent(undefined);`
`const signedEvent = await window.nostr.signEvent({a: 1});`

### Screenshots [optional]

_No response_

### Steps To Reproduce

1. call `window.nostr.enable()`
2. Execute one of the following:

`const signedEvent = await window.nostr.signEvent(undefined);`
`const signedEvent = await window.nostr.signEvent({a: 1});`

### Expected behavior

Alby throws an exception saying the input is not a valid nostr event.

### Alby information

Alby 2.0.1

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

None

### PR DESCRIPTION
**Pull request by mquasar**
### Describe the changes you have made in this PR

Updated validateEvent with latest nostr-tool version and changes do signEventOrPrompt to return error in case of invalid events

### Link this PR to an issue [optional]

Fixes  #2446

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

1. call window.nostr.enable()
2. Execute one of the following:

```
const signedEvent = await window.nostr.signEvent(undefined);
const signedEvent = await window.nostr.signEvent({a: 1});

```
### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [ ] New and existing tests pass locally with my changes
- [ ] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

File: src/extension/background-script/actions/nostr/signEventOrPrompt.ts [hunk 1]
```diff
@@ -47,6 +44,8 @@ const signEventOrPrompt = async (message: MessageSignEvent) => {
       }
     }
 
+    if (!event.id) event.id = nostr.getEventHash(event);
```
Comment (rolznz) [inline src/extension/background-script/actions/nostr/signEventOrPrompt.ts:47]: I think we should always set the pubkey and id. The pubkey must be the pubkey of the event creator, and the ID can only be generated once all fields including the pubkey are set on the event.

**important** the pubkey must be set in order to calculate the event ID. When you moved them you swapped the order around which will break `getEventHash`.

Comment (fczuardi) [reply src/extension/background-script/actions/nostr/signEventOrPrompt.ts:47]: nice catch! after we move this to after the validation we swapped pubkey and event.id order, you are right, the event id should be after everything else is part of the event object

Comment (fczuardi) [reply src/extension/background-script/actions/nostr/signEventOrPrompt.ts:47]: as for the "always set the pubkey and id" the idea then is to always override whatever event we receive to sign with the pubkey from alby, makes sense

Comment (rolznz) [reply src/extension/background-script/actions/nostr/signEventOrPrompt.ts]: I think so. Otherwise we need to validate them, and the only way to validate them is to compare against the generated values, so we might as well overwrite them?

File: src/extension/background-script/actions/nostr/helpers.ts [hunk 2]
```diff
@@ -58,14 +58,14 @@ export async function addPermissionFor(method: string, host: string) {
   return !!permissionIsAdded && (await db.saveToStorage());
 }
 
-// from: https://github.com/nbd-wtf/nostr-tools/blob/160987472fd4922dd80c75648ca8939dd2d96cc0/event.ts#L61
+// from: https://github.com/nbd-wtf/nostr-tools/blob/b9a7f814aaa08a4b1cec705517b664390abd3f69/event.ts#L95
 // to avoid the additional dependency
 export function validateEvent(event: Event): boolean {
+  if (!(event instanceof Object)) return false;
```
Comment (rolznz) [inline src/extension/background-script/actions/nostr/helpers.ts:64]: We now have multiple changes from the above link, so maybe we should update the comment to say "based upon"?

**Review by rolznz — APPROVED** [review]
tACK

File: src/extension/background-script/actions/nostr/signEventOrPrompt.ts [hunk 3]
```diff
@@ -47,6 +44,8 @@ const signEventOrPrompt = async (message: MessageSignEvent) => {
       }
     }
 
+    event.pubkey = nostr.getPublicKey();
```
Comment (reneaaron) [inline src/extension/background-script/actions/nostr/signEventOrPrompt.ts:47]: Not sure about this change. Aren't the clients supposed to fill this event object? 

I think we should only override those properties if they are not set: 

https://github.com/fiatjaf/nos2x/blob/master/extension/background.js#L170-L171

Comment (reneaaron) [reply src/extension/background-script/actions/nostr/signEventOrPrompt.ts:47]: Signing clients are supposed to fill those fields according to the spec here: 

https://github.com/nostr-protocol/nips/blob/master/07.md

> // takes an event object, adds `id`, `pubkey` and `sig` and returns it

I'd say we just fill them if they are empty :+1:

Comment (mquasar) [reply src/extension/background-script/actions/nostr/signEventOrPrompt.ts]: Ok, just commited a new version with the checks back.

**Review by rolznz — APPROVED** [review]

**Review by reneaaron — APPROVED** [review]
tACK
