### PR TITLE
fix: don't allow to bypass unlock screen and access welcome screen

### LINKED ISSUE #2915: Prevent opening the welcome screen when already initialized
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently it is possible to manually open the welcome screen even though the onboarding is already finished

### Screenshots [optional]

This should be prevented and the user should be on all routes of the welcome screen be redirected to the options page.

### Steps To Reproduce

visit welcome.html manually

### Expected behavior

redirect to options.html

### Alby information

Alby 3.4.1

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

None

### PR DESCRIPTION
**Pull request by pavanjoshi914**
### Describe the changes you have made in this PR

security fix to not allow to bypass unlock screen and read unsensitive data

### Link this PR to an issue [optional]

Fixes  #2915 

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

try to access welcome.html when the extension is unlocked and locked. 
### Checklist

- [X] Self-review of changed code
- [X] Manual testing
- [X] Added automated tests where applicable
- [X] Update Docs & Guides
- For UI-related changes
- [X] Darkmode
- [X] Responsive layout

### CODE REVIEW

File: src/app/router/Welcome/Welcome.tsx [hunk 1]
```diff
@@ -17,34 +18,36 @@ const connectorRoutes = getConnectorRoutes();
...
-                      title={i18n.t("translation:choose_connector.title")}
-                      description={i18n.t(
-                        "translation:choose_connector.description"
-                      )}
-                      connectorRoutes={connectorRoutes}
-                    />
-                  }
-                ></Route>
-                {renderRoutes(connectorRoutes)}
+      <AccountProvider>
```
Comment (bumi) [inline src/app/router/Welcome/Welcome.tsx:21]: why do we need the AccountProvider here?

Comment (pavanjoshi914) [reply src/app/router/Welcome/Welcome.tsx:21]: cause AccountContext has all the logic to handle this. we use AccountProvider in options router as well to handle the such case

Comment (pavanjoshi914) [reply src/app/router/Welcome/Welcome.tsx:21]: https://github.com/getAlby/lightning-browser-extension/pull/2928/files#diff-4cbea9de97e0df6000b0839d65825e3f81f7a5cdf85eed529d3adeadaba37ee0R143

Comment (pavanjoshi914) [reply src/app/router/Welcome/Welcome.tsx:21]: but that didn't handled the case when extension is locked and user wants to access any route. made little corrections in accountProvider.

Comment (pavanjoshi914) [reply src/app/router/Welcome/Welcome.tsx:21]: now we support both. 
1. if extension is locked and user tries to access the screen - redirect to options page. now options router has security checks  so it will redirect to unlock page by default

2. if extension is unlocked and user tried to access welcome page. we redirec to options.html/wallet - as now we are wrapping welcome router under accountProvider. and provider has that checks

so it solves both

**Review by reneaaron — APPROVED** [review]
tACK
