### PR TITLE
fix: receive back button

### LINKED ISSUE #1542: Clicking on back button should go to the previous window
### Describe the bug

Generate an invoice and click back button, should go to previous window and not to home window.

### Screenshots

https://user-images.githubusercontent.com/1178856/192901751-4bda697f-9692-4b34-8ed9-4f3b3df08aa7.mp4

### To Reproduce

1. Click on receive button
2. Generate an invoice
3. Click on back button

### Expected behavior

Not go to home window but to the previous window

### Alby information

- Alby Version: 1.16.1

### PR DESCRIPTION
**Pull request by manavdesai27**
### Describe the changes you have made in this PR
  
  Changed back button functionality to go back to previous screen rather than home in receive screen.
  
  ### Link this PR to an issue [optional]
  
  Fixes #1542 
  
  ### Type of change
  
  - `fix`: Bug fix (non-breaking change which fixes an issue)
  
  ### Screenshots of the changes [optional]
  
  
  https://user-images.githubusercontent.com/74018438/218330325-13b58007-ecb3-41a9-8d72-e782b9d79e18.mp4
  
  
  
  ### How has this been tested?
  
  _Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_
  
  ### Checklist
  
  - [x] My code follows the style guidelines of this project and performed a self-review of my own code
  - [x] New and existing tests pass locally with my changes
  - [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by manavdesai27** [comment]
@escapedcat @im-adithya I am closing the other pull request and opening this one in place of it, for a clean working tree.

**Comment by im-adithya** [comment]
Can you please add me as a collaborator on your repo?

**Comment by escapedcat** [comment]
> Sure I don't mind. But may I ask why?

@im-adithya didn't (doesn't yet?) have the permissions via the Alby team. The Alby team can pushg into your PR. He wanted to support you with the merghe/rebase I believe.

**Comment by manavdesai27** [comment]
@escapedcat Could you provide a review on this PR?

**Review by escapedcat — APPROVED** [review]

File: src/app/screens/Receive/index.tsx [hunk 1]
```diff
@@ -112,6 +112,21 @@ function Receive() {
...
+    setFormData({
+      amount: "0",
+      description: "",
+      expiration: "",
+    });
+    setPaid(false);
+    setPollingForPayment(false);
+    setInvoice(null);
+  }
+
```
Comment (im-adithya) [inline src/app/screens/Receive/index.tsx:129]: We can DRY this up by using a function called
```
setDefaults() {
    setFormData({
      amount: "0",
      description: "",
      expiration: "",
    });
    setPaid(false);
    setPollingForPayment(false);
    setInvoice(null);
}

Comment (manavdesai27) [reply src/app/screens/Receive/index.tsx:129]: Will do!

File: src/app/screens/Receive/index.tsx [hunk 2]
```diff
@@ -223,7 +238,7 @@ function Receive() {
         title={t("title")}
         headerLeft={
           <IconButton
-            onClick={() => navigate("/")}
+            onClick={handleBack}
```
Comment (im-adithya) [inline src/app/screens/Receive/index.tsx:241]: Also, we can use it like this here:
```
onClick={() => {
    invoice ? setDefaults() : navigate("/");
}}

and
```
onClick={() => {
    setDefaults();
    navigate("/receive");
}}

to avoid having `handleBack` and `receiveAnotherPayment` functions

Comment (manavdesai27) [reply src/app/screens/Receive/index.tsx]: Done! @im-adithya

**Review by im-adithya — APPROVED** [review]
