### PR TITLE
fix: add descriptive message when method is not supported

### LINKED ISSUE #961: Correct error message when keysend is not supported
**Describe the bug**
Currently BlueWallet's LndHub does not support keysend payments. 
Our lndhub connector still tries to send a keysend API call which fails with a 404 but we do not give the user a good error message.

We should tell the user that this method is not supported by the connected account. 

**To Reproduce**
1. Connect a BlueWallet lndhub
2. Try to do a keysend payment

**Expected behavior**
Indicate that the connected account does not support the requested method.

### PR DESCRIPTION
**Pull request by dylancom**
#### Link this PR to an issue
Fixes #961

#### Type of change (Remove other not matching type)

- Bug fix (non-breaking change which fixes an issue)

#### Describe the changes you have made in this PR -
Shows: "keysend not supported by the connected account." when not available. Instead of 404.

### CODE REVIEW

File: src/extension/background-script/connectors/lndhub.ts [hunk 1]
```diff
@@ -352,6 +352,10 @@ export default class LndHub implements Connector {
 
       if (axios.isAxiosError(e)) {
         const errResponse = e.response as AxiosResponse;
+        if (errResponse?.status === 404) {
+          const method = path.replace("/", "");
+          throw new Error(`${method} not supported by the connected account.`);
```
Comment (escapedcat) [inline src/extension/background-script/connectors/lndhub.ts:357]: Will the user be informed by this as well?

Comment (dylancom) [reply src/extension/background-script/connectors/lndhub.ts:357]: Yes, the user will see this in the new Toast

**Review by escapedcat — APPROVED** [review]

**Review by bumi — APPROVED** [review]
utACK. looks good!
