### PR TITLE
fix: format error in signup

### LINKED ISSUE #1967: JSON in signup error message
When entering the wrong password for your account you will see a JSON string at the end of the error message. 

image

Also the error message probably is wrong (cc @bumi) because we allow both the lightning address and the email to login, right?

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Formats the error message during signup.

### Link this PR to an issue [optional]

Fixes #1967

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]

Screenshot 2023-01-26 at 4 21 42 PM

### How has this been tested?

Manually

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

File: src/app/screens/connectors/AlbyWallet/index.tsx [hunk 1]
```diff
@@ -85,9 +85,22 @@ export default function AlbyWallet({ variant }: Props) {
...
-                data
-              )}`
+              <p>
+                {t("pre_connect.errors.create_wallet_error1")}
+                <br />
+                {t("pre_connect.errors.create_wallet_error2")}
+                <br />
+                {Object.keys(data).map((rule, index) => {
+                  return (
+                    <p key={"rule-" + index}>
```
Comment (escapedcat) [inline src/app/screens/connectors/AlbyWallet/index.tsx:95]: Can template literals be used?

File: src/app/screens/connectors/AlbyWallet/index.tsx [hunk 2]
```diff
@@ -85,9 +85,22 @@ export default function AlbyWallet({ variant }: Props) {
...
+                      {rule.charAt(0).toUpperCase() + rule.slice(1)}
```
Comment (escapedcat) [inline src/app/screens/connectors/AlbyWallet/index.tsx:96]: No exactly sure but if this is "uppercasing" the first letter this could be done with CSS maybe?: https://stackoverflow.com/a/5577380

**Comment by reneaaron** [comment]
Can we improve the formatting of the message somehow? 

image

What do you think of having it this way: 

```
Error message (detailed error message)

If you need help, please contact support@getalby.com
```

So in this case: 

```
Failed to login (Email - must be your...)

If you need help, please contact support@getalby.com
```

I don't really get this specific error, though. You should be able to login with your email as well as with your lightning address (that's also what we indicate in the form):
image

**Comment by im-adithya** [comment]
> I don't really get this specific error, though. You should be able to login with your email as well as with your lightning address (that's also what we indicate in the form):

Yeah, I was doing it on purpose by using `yarn run dev:chrome` without the WALLET_CREATE_URL



> So in this case:

> ```
> Failed to login (Email - must be your...)
> 
> If you need help, please contact support@getalby.com

But it's breaking into the next line leaving empty spaces

**Comment by escapedcat** [comment]
Yeah. this looks a bit weird because it's everything in one line?
image

**Comment by im-adithya** [comment]
Yes, so shall we proceed with the changes as is?

**Comment by escapedcat** [comment]
Is it possible to add a `<br>` or `-` after "..., please contact support@getalby.com"?  
Sorry, I tried to express that with my comment.

**Review by escapedcat — APPROVED** [review]
ack
